server:
  port: 8081
spring:
  application:
    name: springcloud-service-consumer
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://eureka8083:8082/eureka/,http://eureka8083:8083/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'