server:
  port: 7079
spring:
  application:
    name: springcloud-service-provider
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1.0
eureka:
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://eureka8083:8082/eureka/,http://eureka8083:8083/eureka/

hello: hello from 7079